(require 'meow)

(meow-global-mode 1)
(meow-setup-indicator)

(defun meow-setup()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
  (meow-normal-define-key
   '("i" . previous-line)
   '("k" . next-line)
   '("j" . meow-left)
   '("l" . meow-right)
   '("u" . meow-back-word)
   '("o" . forward-word)
   '("h" . beginning-of-line)
   '(";" . end-of-line)
   '("f" . meow-insert)
   '("m" . set-mark-command)
   '("." . meow-reverse)
   '("c" . meow-save)
   '("x" . meow-kill)
   '("v" . meow-yank)
   '("V" . meow-yank-pop)
   '("z" . meow-undo)
   '("gl" . goto-line)
   '("gg" . meow-grab)
   '("8" . meow-extend)
   '("dd" . meow-kill-whole-line)
   '("dl" . meow-C-k)
   '("df" . meow-C-d)
   '("G" . meow-kill-whole-line)
   )
  )

(meow-setup)

(provide 'init-meow)
